Update Afterpay API version to V2
workarea-commerce/workarea-afterpay pull request #1
Opened 2019-09-04 15:46 UTC by jyucis

New API version allows for a traditional auth then capture
model of handling payments

2019-09-05 19:42 UTC, eric-pigeon requested changes

2019-09-05 19:42 UTC, eric-pigeon commented on README.md
> +Workarea Blog is released under the [Business Software License](LICENSE)
Blog -> Afterpay

2019-09-12 20:57 UTC, meowsus approved these changes

2019-09-12 20:57 UTC, meowsus commented
I think this is good to be merged @jyucis

2019-09-16 13:10 UTC, bencrouse commented
What are we doing with this @eric-pigeon @jyucis ?

2019-09-16 13:44 UTC, jyucis commented
I'd like to get @eric-pigeon to take a look before we merge.

2019-09-16 15:31 UTC, eric-pigeon requested changes
You aren't handling timeout issues on any external HTTP interactions with afterpay.  From the afterpay documentation the authorize, and capture actions are idempotent.  We should at the very least rescue any http timeout errors and retry them at least once, then properly fail and persisted a failed transaction.

2019-09-19 13:15 UTC, bencrouse commented
@jyucis can you wrap this up? Let's try to finish work in progress.

2019-09-20 16:56 UTC, meowsus commented
@jyucis @eric-pigeon I'm assuming this work is for the next patch: v2.0.3

Let me know if my assumption is far from correct.

2019-09-20 18:07 UTC, eric-pigeon commented
I think this work for a new major since we updating to a new major for the afterpay API

2019-10-02 13:27 UTC, bencrouse commented
@eric-pigeon where are we at with your review? Would you take a look?

2019-10-02 15:50 UTC, eric-pigeon requested changes

2019-10-02 15:50 UTC, eric-pigeon commented on README.md
> +WebLinc Platform Documentation
Workarea?

2019-10-03 16:42 UTC, merged